/**
 * All the chain interaction for the counter UI, kept out of the React layer.
 *
 * Deliberately mirrors apps/counter/src/deploy.ts, which is the Node version of
 * the same sequence. If the two ever disagree, the Node script is the reference:
 * it is the toolchain proof.
 */

import { deployContract, findDeployedContract } from '@midnight-ntwrk/midnight-js-contracts';
import { CompiledContract } from '@midnight-ntwrk/midnight-js-protocol/compact-js';
import type { MidnightProviders } from '@midnight-ntwrk/midnight-js-types';
import { LOCALNET_GENESIS_SEEDS } from '@mra/network';
import { currentNetwork } from '@mra/lab-shell';
import {
  configureNetworkId,
  createWalletFromSeed,
  encodeWalletAddresses,
  type MidnightWallet,
} from '@mra/wallet';
import { createBrowserProviders } from '@mra/wallet/providers/browser';

import { Contract, ledger } from '@mra/app-counter/contract';

/** Served by Vite from web/public/managed — see vite.config.ts. */
const ZK_CONFIG_BASE_URL = `${globalThis.location.origin}/managed`;

const PRIVATE_STATE_PASSWORD = 'Localnet-Dev-Pw-2026!';

export type CircuitId = 'increment';

const compiledContract = CompiledContract.make('counter', Contract).pipe(
  CompiledContract.withVacantWitnesses,
  // Relative, because assets are fetched from the served base URL, not from disk.
  CompiledContract.withCompiledFileAssets(''),
);

export interface Session {
  readonly wallet: MidnightWallet;
  readonly providers: MidnightProviders<CircuitId>;
  readonly shieldedAddress: string;
  readonly shieldedBalance: bigint;
  readonly unshieldedAddress: string;
  readonly unshieldedBalance: bigint;
  readonly dustAddress: string;
  /**
   * DUST balance in SPECKS at a point in time. A function, not a number: DUST
   * is generated by holding NIGHT and decays, so the balance is computed from
   * chain state for the moment you ask about.
   */
  readonly dustBalance: (time: Date) => bigint;
}

/**
 * Build a wallet and providers entirely in the browser.
 *
 * On localnet the caller passes a genesis seed index; on Stagenet it passes a
 * faucet-funded seed the USER typed — such a seed is never hardcoded and never
 * persisted by this app.
 */
export async function connect(seedOrIndex: number | string = 0): Promise<Session> {
  const network = currentNetwork();
  await configureNetworkId(network);

  const seed =
    typeof seedOrIndex === 'string'
      ? seedOrIndex.trim().toLowerCase().replace(/^0x/, '')
      : (LOCALNET_GENESIS_SEEDS[seedOrIndex] ?? LOCALNET_GENESIS_SEEDS[0]!);
  const wallet = await createWalletFromSeed(seed, network);
  const state = await wallet.wallet.waitForSyncedState();

  const providers = await createBrowserProviders<CircuitId>({
    network,
    wallet,
    zkConfigBaseUrl: ZK_CONFIG_BASE_URL,
    privateStateStoreName: 'counter-private-state',
    accountId: `counter-${seed.slice(0, 8)}`,
    privateStatePassword: PRIVATE_STATE_PASSWORD,
  });

  const nativeToken = '0'.repeat(64);
  const addresses = encodeWalletAddresses(state, network);
  return {
    wallet,
    providers,
    shieldedAddress: addresses.shielded,
    shieldedBalance: BigInt(state.shielded.balances?.[nativeToken] ?? 0n),
    unshieldedAddress: addresses.unshielded,
    unshieldedBalance: BigInt(state.unshielded.balances?.[nativeToken] ?? 0n),
    dustAddress: addresses.dust,
    dustBalance: (time) => state.dust.balance(time),
  };
}

/** Deploy a fresh counter. Returns its address. */
export async function deploy(session: Session): Promise<string> {
  const deployed = await deployContract(session.providers, { compiledContract });
  return deployed.deployTxData.public.contractAddress;
}

/** Read the public `round` value straight from the indexer. */
export async function readRound(session: Session, address: string): Promise<bigint | null> {
  const state = await session.providers.publicDataProvider.queryContractState(address);
  return state ? BigInt(ledger(state.data).round) : null;
}

/** Call increment() on an existing contract. Proves client-side, then submits. */
export async function increment(
  session: Session,
  address: string,
): Promise<{ txId: string; blockHeight: number }> {
  const found = await findDeployedContract(session.providers, {
    contractAddress: address,
    compiledContract,
  });
  const call = await found.callTx.increment();
  return { txId: call.public.txId, blockHeight: call.public.blockHeight };
}
