/**
 * Counter UI — the toolchain proof, in a browser.
 *
 * Everything here happens client-side: the wallet is built in the page, proofs
 * are generated by the local proof server, and state is read from the indexer.
 * There is no backend.
 *
 * The log is the point. Each step is timed and shown, because "design for
 * minutes" is a real constraint and an interface that hides it is lying.
 */

import { useCallback, useEffect, useRef, useState } from 'react';

import Contracts from './Contracts.tsx';
import { connect, deploy, increment, readRound, type Session } from './counter.ts';
import {
  forget,
  getGenesisHash,
  loadChecked,
  remember,
  type CheckedContract,
} from './history.ts';
import Infrastructure from './Infrastructure.tsx';

type Status = 'idle' | 'connecting' | 'ready' | 'working' | 'error';

/** Best-effort readable form for a non-Error thrown value. */
function describe(value: unknown): string {
  if (typeof value === 'string') return value;
  try {
    const json = JSON.stringify(value, (_k, v) => (typeof v === 'bigint' ? v.toString() : v));
    if (json && json !== '{}') return json.slice(0, 400);
  } catch {
    /* fall through */
  }
  return String(value);
}

interface LogLine {
  readonly text: string;
  readonly kind: 'info' | 'ok' | 'error';
  readonly ms?: number;
}

export default function App() {
  const [status, setStatus] = useState<Status>('idle');
  const [session, setSession] = useState<Session | null>(null);
  const [address, setAddress] = useState<string | null>(null);
  const [round, setRound] = useState<bigint | null>(null);
  const [log, setLog] = useState<readonly LogLine[]>([]);
  const [contracts, setContracts] = useState<readonly CheckedContract[]>([]);
  const logBox = useRef<HTMLDivElement>(null);

  const say = useCallback((text: string, kind: LogLine['kind'] = 'info', ms?: number) => {
    setLog((prev) => [...prev, { text, kind, ms }]);
  }, []);

  // Set scrollTop rather than scrollIntoView: on a fixed (overflow:hidden) page
  // scrollIntoView still scrolls ANCESTORS programmatically, which shoves the
  // header off-screen with no way for the user to scroll it back.
  useEffect(() => {
    const box = logBox.current;
    if (box) box.scrollTop = box.scrollHeight;
  }, [log]);

  /**
   * Re-check history against the current chain.
   *
   * Needs a session because reading a round goes through the providers. Before
   * connect, history is listed but rounds and liveness are unknown — which is why
   * this is called again right after connecting.
   */
  const refreshContracts = useCallback(
    async (current: Session | null) => {
      const next = await loadChecked(async (address) =>
        current ? await readRound(current, address) : null,
      );
      setContracts(next);
    },
    [],
  );

  useEffect(() => {
    void refreshContracts(null);
  }, [refreshContracts]);

  /** Run a step, timing it and reporting failure rather than swallowing it. */
  const step = useCallback(
    async <T,>(label: string, fn: () => Promise<T>): Promise<T | undefined> => {
      const started = Date.now();
      say(`${label}…`);
      try {
        const result = await fn();
        say(label, 'ok', Date.now() - started);
        return result;
      } catch (error) {
        // Unwrap the cause chain. This stack wraps failures in terse messages
        // ("Transaction submission error") and buries the real reason in `cause`
        // — and that cause is often an Effect tagged error, NOT an Error, so an
        // `instanceof Error` walk stops before reaching anything useful.
        const parts: string[] = [];
        let current: unknown = error;
        for (let depth = 0; current != null && depth < 6; depth += 1) {
          const record = current as { message?: unknown; _tag?: unknown; cause?: unknown };
          const tag = typeof record._tag === 'string' ? `[${record._tag}] ` : '';
          const message =
            typeof record.message === 'string' && record.message
              ? record.message
              : describe(current);
          parts.push(`${tag}${message}`);
          current = record.cause;
        }
        if (parts.length === 0) parts.push(String(error));
        // Effect wraps failures in ways that hide the reason from both `message`
        // and `cause`. When the chain yields nothing useful, dump the error's own
        // properties so the real fault is visible instead of guessed at.
        if (parts.length < 2 && error != null) {
          // Effect rejects with a FiberFailure whose real Cause hangs off a
          // SYMBOL, invisible to both `cause` and getOwnPropertyNames.
          for (const symbol of Object.getOwnPropertySymbols(error)) {
            const value = (error as unknown as Record<symbol, unknown>)[symbol];
            parts.push(`${String(symbol)}: ${describe(value)}`);
          }
          for (const key of Object.getOwnPropertyNames(error)) {
            if (key === 'message' || key === 'stack') continue;
            parts.push(`${key}: ${describe((error as Record<string, unknown>)[key])}`);
          }
        }
        say(`${label} failed: ${parts.join('\n  ↳ ')}`, 'error');
        setStatus('error');
        return undefined;
      }
    },
    [say],
  );

  const onConnect = async () => {
    setStatus('connecting');
    const next = await step('Build wallet and sync', () => connect(0));
    if (!next) return;
    setSession(next);
    say(`Unshielded balance ${next.unshieldedBalance.toLocaleString()}`, 'ok');
    await refreshContracts(next);
    setStatus('ready');
  };

  /**
   * Deploy, record, and select — the single implementation.
   *
   * Takes the session explicitly so autorun can use it too. Keeping this in one
   * place matters: when the button and autorun each had their own copy, only the
   * button remembered the contract, so autorun deployments never reached history.
   */
  const deployAndRecord = useCallback(
    async (current: Session): Promise<string | undefined> => {
      const deployedAt = await step('Deploy counter (prove + submit)', () => deploy(current));
      if (!deployedAt) return undefined;
      setAddress(deployedAt);

      // Tag the entry with the chain it belongs to, so a localnet reset can be
      // detected later rather than offering a dead address as usable.
      try {
        remember(deployedAt, await getGenesisHash());
      } catch {
        say('could not record contract in history', 'error');
      }

      setRound((await step('Read round', () => readRound(current, deployedAt))) ?? null);
      await refreshContracts(current);
      return deployedAt;
    },
    [refreshContracts, say, step],
  );

  const onDeploy = async () => {
    if (!session) return;
    setStatus('working');
    await deployAndRecord(session);
    setStatus('ready');
  };

  /** Switch to a previously deployed contract. */
  const onSelect = async (next: string) => {
    if (!session || next === address) return;
    setStatus('working');
    setAddress(next);
    setRound(null);
    say(`switched to ${next.slice(0, 10)}…`);
    const current = await step('Read round', () => readRound(session, next));
    setRound(current ?? null);
    setStatus('ready');
  };

  const onForget = (target: string) => {
    forget(target);
    if (target === address) {
      setAddress(null);
      setRound(null);
    }
    void refreshContracts(session);
  };

  const onIncrement = async () => {
    if (!session || !address) return;
    setStatus('working');
    const result = await step('increment() (prove + submit)', () => increment(session, address));
    if (!result) return;
    say(`tx ${result.txId.slice(0, 18)}… @ block ${result.blockHeight}`, 'ok');
    const next = await step('Read round', () => readRound(session, address));
    setRound(next ?? null);
    // Refresh the list too, or its per-contract rounds go stale the moment you
    // increment — the card would say 1 while the row still claimed 0.
    await refreshContracts(session);
    setStatus('ready');
  };

  const busy = status === 'connecting' || status === 'working';

  /**
   * `?autorun` runs connect → deploy → increment on load.
   *
   * This exists so the whole flow can be verified in a headless browser, where
   * nothing can click. It is opt-in via the query string and never fires during
   * normal use.
   */
  const autorunStarted = useRef(false);
  useEffect(() => {
    if (autorunStarted.current) return;
    if (!new URLSearchParams(globalThis.location.search).has('autorun')) return;
    autorunStarted.current = true;

    void (async () => {
      say('autorun: connect → deploy → increment');
      const s = await step('Build wallet and sync', () => connect(0));
      if (!s) return;
      setSession(s);
      say(`Unshielded balance ${s.unshieldedBalance.toLocaleString()}`, 'ok');

      const at = await deployAndRecord(s);
      if (!at) return;

      const result = await step('increment() (prove + submit)', () => increment(s, at));
      if (!result) return;
      say(`tx ${result.txId.slice(0, 18)}… @ block ${result.blockHeight}`, 'ok');
      setRound((await step('Read round', () => readRound(s, at))) ?? null);
      await refreshContracts(s);
      setStatus('ready');
      say('autorun complete', 'ok');
    })();
  }, [deployAndRecord, refreshContracts, say, step]);

  return (
    <main>
      <header>
        <h1>Counter</h1>
        <p className="sub">
          Midnight toolchain proof — compile, deploy, prove, submit, read back. Entirely
          client-side against localnet.
        </p>
      </header>

      {/* Two columns so the whole thing fits one screen. Only the activity log
          and the log drawers scroll; the page itself never does. */}
      <div className="columns">
      <div className="col">
      <section className="grid">
        <div className="card">
          <span className="label">Round</span>
          <span className="value">{round === null ? '—' : round.toString()}</span>
        </div>
        <div className="card">
          <span className="label">Contract</span>
          <span className="value mono small">
            {address ? `${address.slice(0, 10)}…${address.slice(-6)}` : 'not deployed'}
          </span>
        </div>
        <div className="card">
          <span className="label">Wallet</span>
          <span className="value mono small">
            {session ? `${session.unshieldedBalance.toLocaleString()} unshielded` : 'not connected'}
          </span>
        </div>
      </section>

      <section className="actions">
        <button onClick={onConnect} disabled={busy || !!session}>
          {session ? 'Connected' : 'Connect wallet'}
        </button>
        <button onClick={onDeploy} disabled={busy || !session}>
          {contracts.some((c) => c.state === 'live') ? 'Deploy another' : 'Deploy counter'}
        </button>
        <button onClick={onIncrement} disabled={busy || !session || !address}>
          increment()
        </button>
      </section>

      <Contracts
        contracts={contracts}
        active={address}
        busy={busy}
        onSelect={(next) => void onSelect(next)}
        onForget={onForget}
        onRefresh={() => void refreshContracts(session)}
      />

      <section className="log" aria-live="polite" ref={logBox}>
        {log.length === 0 && <p className="muted">Connect a wallet to begin.</p>}
        {log.map((line, i) => (
          <p key={i} className={line.kind}>
            <span>{line.text}</span>
            {line.ms !== undefined && <span className="ms">{(line.ms / 1000).toFixed(1)}s</span>}
          </p>
        ))}
        {busy && <p className="muted">working — proving takes ~20s, do not reload</p>}
      </section>

      </div>

      <div className="col">
        <Infrastructure />
      </div>
      </div>

      <footer>
        <p className="muted small">
          Localnet only. Well-known genesis seed, never a funded key. Proofs are generated by the
          local proof server; nothing secret leaves this machine.
        </p>
      </footer>
    </main>
  );
}
