/**
 * Midnight DeFi Dashboard — the counter toolchain proof, in the Midnight brand.
 *
 * Everything here happens client-side: the wallet is built in the page, proofs
 * are generated by the local proof server, and state is read from the indexer.
 * There is no backend.
 *
 * The log is the point. Each step is timed and shown, because "design for
 * minutes" is a real constraint and an interface that hides it is lying. The
 * operation bar above it names the phase a call is in — proving is sub-second;
 * the ~18 s is block inclusion, and a bare spinner at that latency reads as a
 * hang and invites a second click.
 */

import { useCallback, useEffect, useRef, useState } from 'react';

import {
  breakdownWindow,
  describeBreakdown,
  getNetwork,
  type ProvingBreakdown,
} from '@mra/network';

import Contracts from './Contracts.tsx';
import { connect, deploy, increment, readRound, type Session } from './counter.ts';
import {
  forget,
  getGenesisHash,
  loadChecked,
  remember,
  type CheckedContract,
} from './history.ts';
import { getProvingObserver } from './infra.ts';
import Infrastructure from './Infrastructure.tsx';
import LogoMark from './Logo.tsx';

type Status = 'idle' | 'connecting' | 'ready' | 'working' | 'error';

/** Personas map onto the four localnet genesis seeds. */
const PERSONAS = ['Alice', 'Bob', 'Eve', 'Dana'] as const;

const OP_PHASES = ['proving', 'submitting', 'awaiting inclusion', 'reading back'] as const;

interface Operation {
  readonly label: string;
  readonly phase: number;
  readonly startedAt: number;
  /** Proving-meter call count when the operation began, so the live timing bar
   *  and the final breakdown only see this operation's proofs. */
  readonly callsBefore: number;
}

/**
 * The timing bar: one operation's wall-clock, split into its honest parts.
 *
 * Proving is ~2% of the bar, and that is the entire message — the segment is
 * kept visible with a min-width, and the legend carries the exact numbers.
 * Segment identity is fixed order + label, never colour alone.
 */
function TimingBar({ b, live }: { readonly b: ProvingBreakdown; readonly live: boolean }) {
  const total = Math.max(1, b.prepareMs + b.provingMs + b.inclusionMs);
  const width = (ms: number) => `${Math.max(0, (ms / total) * 100)}%`;
  const s = (ms: number, digits = 1) => `${(ms / 1000).toFixed(digits)}s`;
  const pending = live && b.provingCalls === 0;
  return (
    <div className="timing">
      <div
        className="timing-bar"
        role="img"
        aria-label={`prepare ${s(b.prepareMs)}, proving ${s(b.provingMs, 2)}, submit and inclusion ${s(b.inclusionMs)}`}
      >
        <span className="seg prepare" style={{ width: width(b.prepareMs) }} />
        {b.provingMs > 0 && <span className="seg proving" style={{ width: width(b.provingMs) }} />}
        {b.inclusionMs > 0 && (
          <span className="seg inclusion" style={{ width: width(b.inclusionMs) }} />
        )}
      </div>
      <div className="timing-legend">
        <span>
          <i className="chip prepare" />
          prepare {s(b.prepareMs)}
        </span>
        <span>
          <i className="chip proving" />
          proving {pending ? '…' : s(b.provingMs, 2)}
          {b.provingCalls > 1 ? ` (${b.provingCalls} calls)` : ''}
        </span>
        <span>
          <i className="chip inclusion" />
          submit + inclusion {pending ? '…' : s(b.inclusionMs)}
        </span>
      </div>
    </div>
  );
}

const THEME_KEY = 'mdd.theme.v1';

/** Best-effort readable form for a non-Error thrown value. */
function describe(value: unknown): string {
  if (typeof value === 'string') return value;
  try {
    const json = JSON.stringify(value, (_k, v) => (typeof v === 'bigint' ? v.toString() : v));
    if (json && json !== '{}') return json.slice(0, 400);
  } catch {
    /* fall through */
  }
  return String(value);
}

interface LogLine {
  readonly text: string;
  readonly kind: 'info' | 'ok' | 'error';
  readonly ms?: number;
}

const short = (value: string, head = 10, tail = 6) =>
  `${value.slice(0, head)}…${value.slice(-tail)}`;

function copyText(value: string): void {
  try {
    void navigator.clipboard.writeText(value);
  } catch {
    /* clipboard unavailable (permissions, http) — copying is a convenience */
  }
}

export default function App() {
  const [theme, setTheme] = useState<'dark' | 'light'>(() => {
    try {
      return localStorage.getItem(THEME_KEY) === 'light' ? 'light' : 'dark';
    } catch {
      return 'dark';
    }
  });
  const [status, setStatus] = useState<Status>('idle');
  const [persona, setPersona] = useState(0);
  const [sessions, setSessions] = useState<Readonly<Record<number, Session>>>({});
  const [address, setAddress] = useState<string | null>(null);
  const [round, setRound] = useState<bigint | null>(null);
  const [log, setLog] = useState<readonly LogLine[]>([]);
  const [contracts, setContracts] = useState<readonly CheckedContract[]>([]);
  const [genesis, setGenesis] = useState<string | null>(null);
  const [op, setOp] = useState<Operation | null>(null);
  const [lastTiming, setLastTiming] = useState<{
    readonly label: string;
    readonly b: ProvingBreakdown;
  } | null>(null);
  const [now, setNow] = useState(() => Date.now());
  const [logsOn, setLogsOn] = useState(false);
  const logBox = useRef<HTMLDivElement>(null);

  const session = sessions[persona] ?? null;
  const network = getNetwork();
  const isLocalnet = network.networkId === 'undeployed';

  // The brand is dark-first; light is the explicit exception, carried on <html>
  // so the tokens flip everywhere including the body background.
  useEffect(() => {
    document.documentElement.classList.toggle('theme-light', theme === 'light');
    try {
      localStorage.setItem(THEME_KEY, theme);
    } catch {
      /* private browsing */
    }
  }, [theme]);

  // One clock for everything that shows elapsed time or ages.
  useEffect(() => {
    const timer = setInterval(() => setNow(Date.now()), 1000);
    return () => clearInterval(timer);
  }, []);

  const say = useCallback((text: string, kind: LogLine['kind'] = 'info', ms?: number) => {
    setLog((prev) => [...prev, { text, kind, ms }]);
  }, []);

  // Set scrollTop rather than scrollIntoView: on a fixed (overflow:hidden) page
  // scrollIntoView still scrolls ANCESTORS programmatically, which shoves the
  // header off-screen with no way for the user to scroll it back.
  useEffect(() => {
    const box = logBox.current;
    if (box) box.scrollTop = box.scrollHeight;
  }, [log]);

  /**
   * Re-check history against the current chain.
   *
   * Needs a session because reading a round goes through the providers. Before
   * connect, history is listed but rounds and liveness are unknown — which is why
   * this is called again right after connecting.
   */
  const refreshContracts = useCallback(async (current: Session | null) => {
    const next = await loadChecked(async (at) => (current ? await readRound(current, at) : null));
    setContracts(next);
    try {
      setGenesis(await getGenesisHash());
    } catch {
      setGenesis(null);
    }
  }, []);

  useEffect(() => {
    void refreshContracts(null);
  }, [refreshContracts]);

  /** Run a step, timing it and reporting failure rather than swallowing it. */
  const step = useCallback(
    async <T,>(label: string, fn: () => Promise<T>): Promise<T | undefined> => {
      const started = Date.now();
      say(`${label}…`);
      try {
        const result = await fn();
        say(label, 'ok', Date.now() - started);
        return result;
      } catch (error) {
        // Unwrap the cause chain. This stack wraps failures in terse messages
        // ("Transaction submission error") and buries the real reason in `cause`
        // — and that cause is often an Effect tagged error, NOT an Error, so an
        // `instanceof Error` walk stops before reaching anything useful.
        const parts: string[] = [];
        let current: unknown = error;
        for (let depth = 0; current != null && depth < 6; depth += 1) {
          const record = current as { message?: unknown; _tag?: unknown; cause?: unknown };
          const tag = typeof record._tag === 'string' ? `[${record._tag}] ` : '';
          const message =
            typeof record.message === 'string' && record.message
              ? record.message
              : describe(current);
          parts.push(`${tag}${message}`);
          current = record.cause;
        }
        if (parts.length === 0) parts.push(String(error));
        // Effect wraps failures in ways that hide the reason from both `message`
        // and `cause`. When the chain yields nothing useful, dump the error's own
        // properties so the real fault is visible instead of guessed at.
        if (parts.length < 2 && error != null) {
          // Effect rejects with a FiberFailure whose real Cause hangs off a
          // SYMBOL, invisible to both `cause` and getOwnPropertyNames.
          for (const symbol of Object.getOwnPropertySymbols(error)) {
            const value = (error as unknown as Record<symbol, unknown>)[symbol];
            parts.push(`${String(symbol)}: ${describe(value)}`);
          }
          for (const key of Object.getOwnPropertyNames(error)) {
            if (key === 'message' || key === 'stack') continue;
            parts.push(`${key}: ${describe((error as Record<string, unknown>)[key])}`);
          }
        }
        say(`${label} failed: ${parts.join('\n  ↳ ')}`, 'error');
        setStatus('error');
        return undefined;
      }
    },
    [say],
  );

  /**
   * Track a proved call's phases while `fn` runs.
   *
   * The proof server tells us nothing, so "proving" is observed from this page's
   * own POSTs to it (the shared fetch patch). Submission is too fast to observe,
   * so it gets a beat between proving ending and inclusion starting; everything
   * after that until `fn` resolves is the wait for a block.
   */
  const trackOp = useCallback(
    async <T,>(label: string, fn: () => Promise<T>): Promise<T | undefined> => {
      const observer = getProvingObserver();
      const startedAt = Date.now();
      const callsBefore = observer.calls().length;
      setOp({ label, phase: 0, startedAt, callsBefore });
      let provingSeen = false;
      const watcher = setInterval(() => {
        if (observer.proving()) {
          provingSeen = true;
        } else if (provingSeen) {
          clearInterval(watcher);
          setOp((current) => (current ? { ...current, phase: 1 } : current));
          setTimeout(
            () => setOp((current) => (current ? { ...current, phase: 2 } : current)),
            600,
          );
        }
      }, 250);
      try {
        const result = await fn();
        // The measured answer to "how long does proving take", from this
        // operation's actual requests to the prover — logged so it survives
        // in the record, not just in the bar.
        if (result !== undefined) {
          const b = breakdownWindow(observer, callsBefore, startedAt, Date.now());
          if (b) {
            setLastTiming({ label, b });
            say(`  ↳ ${describeBreakdown(b)}`);
          }
        }
        return result;
      } finally {
        clearInterval(watcher);
      }
    },
    [say],
  );

  const endOp = useCallback(() => setOp(null), []);

  const onConnect = async () => {
    if (session) return;
    setStatus('connecting');
    const name = PERSONAS[persona];
    const next = await step(`Create wallet for ${name} (build + sync)`, () => connect(persona));
    if (!next) return;
    setSessions((prev) => ({ ...prev, [persona]: next }));
    say(`Unshielded balance ${next.unshieldedBalance.toLocaleString('en-US')}`, 'ok');
    await refreshContracts(next);
    setStatus('ready');
  };

  const onPersona = (index: number) => {
    if (index === persona || status === 'connecting' || status === 'working') return;
    setPersona(index);
    say(`persona switched to ${PERSONAS[index]} (genesis seed #${index})`);
  };

  /**
   * Deploy, record, and select — the single implementation.
   *
   * Takes the session explicitly so autorun can use it too. Keeping this in one
   * place matters: when the button and autorun each had their own copy, only the
   * button remembered the contract, so autorun deployments never reached history.
   */
  const deployAndRecord = useCallback(
    async (current: Session): Promise<string | undefined> => {
      const deployedAt = await trackOp('Deploy contract', () =>
        step('Deploy counter (prove + submit)', () => deploy(current)),
      );
      if (!deployedAt) {
        endOp();
        return undefined;
      }
      setAddress(deployedAt);

      // Tag the entry with the chain it belongs to, so a localnet reset can be
      // detected later rather than offering a dead address as usable.
      try {
        remember(deployedAt, await getGenesisHash());
      } catch {
        say('could not record contract in history', 'error');
      }

      setOp((current_) => (current_ ? { ...current_, phase: 3 } : current_));
      setRound((await step('Read round', () => readRound(current, deployedAt))) ?? null);
      endOp();
      await refreshContracts(current);
      return deployedAt;
    },
    [endOp, refreshContracts, say, step, trackOp],
  );

  const onDeploy = async () => {
    if (!session) return;
    setStatus('working');
    await deployAndRecord(session);
    setStatus('ready');
  };

  /** Switch to a previously deployed contract. */
  const onSelect = async (next: string) => {
    if (!session || next === address) return;
    setStatus('working');
    setAddress(next);
    setRound(null);
    say(`switched to ${next.slice(0, 10)}…`);
    const current = await step('Read round', () => readRound(session, next));
    setRound(current ?? null);
    setStatus('ready');
  };

  const onForget = (target: string) => {
    forget(target);
    if (target === address) {
      setAddress(null);
      setRound(null);
    }
    void refreshContracts(session);
  };

  const onIncrement = async () => {
    if (!session || !address) return;
    setStatus('working');
    const result = await trackOp('increment()', () =>
      step('increment() (prove + submit)', () => increment(session, address)),
    );
    if (!result) {
      endOp();
      return;
    }
    say(`tx ${result.txId.slice(0, 18)}… @ block ${result.blockHeight}`, 'ok');
    setOp((current) => (current ? { ...current, phase: 3 } : current));
    const next = await step('Read round', () => readRound(session, address));
    setRound(next ?? null);
    endOp();
    // Refresh the list too, or its per-contract rounds go stale the moment you
    // increment — the card would say 1 while the row still claimed 0.
    await refreshContracts(session);
    setStatus('ready');
  };

  const busy = status === 'connecting' || status === 'working';

  /**
   * `?autorun` runs connect → deploy → increment on load.
   *
   * This exists so the whole flow can be verified in a headless browser, where
   * nothing can click. It is opt-in via the query string and never fires during
   * normal use.
   */
  const autorunStarted = useRef(false);
  useEffect(() => {
    if (autorunStarted.current) return;
    if (!new URLSearchParams(globalThis.location.search).has('autorun')) return;
    autorunStarted.current = true;

    void (async () => {
      say('autorun: create wallet → deploy → increment');
      const s = await step(`Create wallet for ${PERSONAS[0]} (build + sync)`, () => connect(0));
      if (!s) return;
      setSessions((prev) => ({ ...prev, 0: s }));
      say(`Unshielded balance ${s.unshieldedBalance.toLocaleString('en-US')}`, 'ok');

      const at = await deployAndRecord(s);
      if (!at) return;

      const result = await trackOp('increment()', () =>
        step('increment() (prove + submit)', () => increment(s, at)),
      );
      if (!result) {
        endOp();
        return;
      }
      say(`tx ${result.txId.slice(0, 18)}… @ block ${result.blockHeight}`, 'ok');
      setOp((current) => (current ? { ...current, phase: 3 } : current));
      setRound((await step('Read round', () => readRound(s, at))) ?? null);
      endOp();
      await refreshContracts(s);
      setStatus('ready');
      say('autorun complete', 'ok');
    })();
  }, [deployAndRecord, endOp, refreshContracts, say, step, trackOp]);

  const liveCount = contracts.filter((c) => c.state === 'live').length;
  const walletRows: readonly { k: string; addr: string | null; bal: string }[] = [
    {
      k: 'unshielded',
      addr: session?.unshieldedAddress ?? null,
      bal: session ? session.unshieldedBalance.toLocaleString('en-US') : 'not created',
    },
    {
      k: 'shielded',
      addr: session?.shieldedAddress ?? null,
      bal: session ? session.shieldedBalance.toLocaleString('en-US') : 'not created',
    },
    {
      k: 'DUST',
      addr: session?.dustAddress ?? null,
      bal: session ? `${session.dustCoins} coins` : 'not created',
    },
  ];

  return (
    <main>
      <header className="topbar">
        <LogoMark className="brand-logo" />
        <div className="brand-text">
          <h1>Midnight DeFi Dashboard</h1>
          <p className="brand-sub">
            Regulated assets on Midnight — deploy, manage, read. Entirely client-side; every value
            below is live chain state.
          </p>
        </div>
        <div className="topbar-right">
          {isLocalnet ? (
            <div
              className="net-pill local"
              title="Local development chain — disposable. A restart is a fresh chain; genesis seeds are public."
            >
              <span className="net-glyph" />
              <span>Local chain</span>
              <span className="net-meta">
                {network.networkId}
                {genesis ? ` · ${genesis.slice(0, 10)}…` : ''}
              </span>
            </div>
          ) : (
            <div
              className="net-pill stage"
              title="Stagenet — persistent public test network. State survives; keys are faucet-funded."
            >
              <span className="net-glyph" />
              <span>STAGENET</span>
              <span className="net-meta">{network.networkId}</span>
            </div>
          )}
          <span className="logs-indicator">{logsOn ? 'logs streaming' : 'logs off'}</span>
          <button className="theme-btn" onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}>
            {theme === 'dark' ? 'Light' : 'Dark'}
          </button>
        </div>
      </header>

      {/* Two columns so the whole thing fits one screen. Only the activity log,
          the contract list, and the log drawers scroll; the page itself never does. */}
      <div className="columns">
        <div className="col">
          <section className="grid">
            <div className="card">
              <span className="label">Round</span>
              <span className="value">{round === null ? '—' : round.toString()}</span>
            </div>
            <div
              className={address ? 'card copyable' : 'card'}
              title={address ? `${address} — click to copy` : 'No contract selected'}
              onClick={() => {
                if (address) {
                  copyText(address);
                  say('contract address copied');
                }
              }}
            >
              <span className="label">Contract</span>
              <span className="value small">{address ? short(address) : 'not deployed'}</span>
            </div>
            <div className="card">
              <span className="label">Wallet — {PERSONAS[persona]}</span>
              <span className="value small">
                {session
                  ? `${session.unshieldedBalance.toLocaleString('en-US')} unshielded`
                  : 'not created'}
              </span>
            </div>
          </section>

          <section className="actions">
            <button className="primary" onClick={onConnect} disabled={busy || !!session}>
              {session ? 'Created' : 'Create wallet'}
            </button>
            <button className="secondary" onClick={onDeploy} disabled={busy || !session}>
              {liveCount > 0 ? 'Deploy another' : 'Deploy contract'}
            </button>
            <button
              className="secondary mono"
              onClick={onIncrement}
              disabled={busy || !session || !address}
            >
              increment()
            </button>
          </section>

          <section className="wallet-panel">
            <div className="wallet-head">
              <h2>Wallet</h2>
              {PERSONAS.map((name, i) => (
                <button
                  key={name}
                  className={i === persona ? 'persona active' : 'persona'}
                  onClick={() => onPersona(i)}
                >
                  {name}
                </button>
              ))}
              <span className="wallet-meta">
                {isLocalnet ? `genesis seed #${persona} · public test seed` : 'faucet-funded seed'}
              </span>
            </div>
            {walletRows.map((row) => (
              <div className="wallet-row" key={row.k}>
                <span className="k">{row.k}</span>
                <span
                  className={row.addr ? 'addr copyable' : 'addr empty'}
                  title={
                    row.addr
                      ? `${row.addr} — click to copy`
                      : `No ${row.k} address yet — create a wallet for ${PERSONAS[persona]}`
                  }
                  onClick={() => {
                    if (row.addr) {
                      copyText(row.addr);
                      say(`${row.k} address copied`);
                    }
                  }}
                >
                  {row.addr ? short(row.addr, 12, 8) : '—'}
                </span>
                <span className="bal">{row.bal}</span>
              </div>
            ))}
          </section>

          <section className="op-bar">
            <div className="op-head">
              <span className="label">Operation</span>
              <div className="phases">
                {OP_PHASES.map((label, i) => (
                  <div key={label} style={{ display: 'flex', alignItems: 'center', gap: 8, minWidth: 0 }}>
                    <span
                      className={
                        op && op.phase === i
                          ? 'phase current'
                          : op && op.phase > i
                            ? 'phase done'
                            : 'phase'
                      }
                    >
                      {label}
                    </span>
                    {i < OP_PHASES.length - 1 && <span className="phase-arrow">→</span>}
                  </div>
                ))}
              </div>
              <span className="op-elapsed">
                {op ? `${((now - op.startedAt) / 1000).toFixed(1)}s` : '—'}
              </span>
            </div>
            {(() => {
              // Live: this operation's window so far. Idle: the last one, frozen.
              if (op) {
                const b = breakdownWindow(getProvingObserver(), op.callsBefore, op.startedAt, now) ?? {
                  prepareMs: now - op.startedAt,
                  provingMs: 0,
                  provingCalls: 0,
                  inclusionMs: 0,
                  totalMs: now - op.startedAt,
                };
                return <TimingBar b={b} live />;
              }
              return lastTiming ? <TimingBar b={lastTiming.b} live={false} /> : null;
            })()}
            <div className="op-caption">
              {op
                ? `${op.label} — ${OP_PHASES[op.phase]}`
                : lastTiming
                  ? `idle — last ${lastTiming.label}: ${describeBreakdown(lastTiming.b)}`
                  : 'idle — no operation in flight · a proved call takes ~18s: proving ~0.3s, block inclusion the rest'}
            </div>
          </section>

          <Contracts
            contracts={contracts}
            active={address}
            busy={busy}
            onSelect={(next) => void onSelect(next)}
            onForget={onForget}
            onRefresh={() => void refreshContracts(session)}
          />

          <section className="log" aria-live="polite" ref={logBox}>
            {log.length === 0 && <p className="muted">Create a wallet to begin.</p>}
            {log.map((line, i) => (
              <p key={i} className={line.kind}>
                <span>{line.text}</span>
                {line.ms !== undefined && <span className="ms">{(line.ms / 1000).toFixed(1)}s</span>}
              </p>
            ))}
            {busy && <p className="working">working — proving takes ~20s, do not reload</p>}
          </section>
        </div>

        <div className="col">
          <Infrastructure onLogsState={setLogsOn} />
        </div>
      </div>

      <footer>
        <LogoMark className="brand-logo" />
        <p>
          Proofs are generated locally by the proof server — witness data never leaves this
          machine.{' '}
          {isLocalnet
            ? 'This local chain’s wallet uses a well-known public test seed, never a funded key.'
            : 'Stagenet keys are faucet-funded — treat chain state as persistent.'}{' '}
          · proving: local (<span className="mono">{network.proofServer}</span>)
        </p>
      </footer>
    </main>
  );
}
