/**
 * Counter — the toolchain proof, in a browser.
 *
 * Everything here happens client-side: the wallet is built in the page, proofs
 * are generated by the local proof server, and state is read from the indexer.
 * There is no backend.
 *
 * The log is the point. Each step is timed and shown, because "design for
 * minutes" is a real constraint and an interface that hides it is lying. The
 * operation bar names the phase a call is in — proving is sub-second; the
 * ~18 s is block inclusion.
 */

import { useCallback, useEffect, useRef, useState } from 'react';

import { getNetwork } from '@mra/network';
import { formatDust, formatNight } from '@mra/wallet';

import Contracts from './Contracts.tsx';
import { connect, deploy, increment, readRound, type Session } from './counter.ts';
import {
  forget,
  getGenesisHash,
  loadChecked,
  remember,
  type CheckedContract,
} from './history.ts';
import Infrastructure from './Infrastructure.tsx';
import LogoMark from './Logo.tsx';
import { OpBar, useOps } from './ops.tsx';
import { Link } from './router.tsx';
import { useTheme } from './theme.ts';

/** Personas map onto the four localnet genesis seeds. */
const PERSONAS = ['Alice', 'Bob', 'Eve', 'Dana'] as const;

const short = (value: string, head = 10, tail = 6) => `${value.slice(0, head)}…${value.slice(-tail)}`;

function copyText(value: string): void {
  try {
    void navigator.clipboard.writeText(value);
  } catch {
    /* clipboard unavailable (permissions, http) — copying is a convenience */
  }
}

export default function CounterPage() {
  const ops = useOps();
  const { status, setStatus, busy, say, step, trackOp, opReadingBack, endOp } = ops;
  const [theme, toggleTheme] = useTheme();
  const [persona, setPersona] = useState(0);
  const [sessions, setSessions] = useState<Readonly<Record<number, Session>>>({});
  const [address, setAddress] = useState<string | null>(null);
  const [round, setRound] = useState<bigint | null>(null);
  const [contracts, setContracts] = useState<readonly CheckedContract[]>([]);
  const [genesis, setGenesis] = useState<string | null>(null);
  const [logsOn, setLogsOn] = useState(false);

  const session = sessions[persona] ?? null;
  const network = getNetwork();
  const isLocalnet = network.networkId === 'undeployed';

  useEffect(() => {
    document.title = 'Counter — Midnight toolchain proof';
  }, []);

  /**
   * Re-check history against the current chain.
   *
   * Needs a session because reading a round goes through the providers. Before
   * connect, history is listed but rounds and liveness are unknown — which is why
   * this is called again right after connecting.
   */
  const refreshContracts = useCallback(async (current: Session | null) => {
    const next = await loadChecked(async (at) => (current ? await readRound(current, at) : null));
    setContracts(next);
    try {
      setGenesis(await getGenesisHash());
    } catch {
      setGenesis(null);
    }
  }, []);

  useEffect(() => {
    void refreshContracts(null);
  }, [refreshContracts]);

  const onConnect = async () => {
    if (session) return;
    setStatus('connecting');
    const name = PERSONAS[persona];
    const next = await step(`Create wallet for ${name} (build + sync)`, () => connect(persona));
    if (!next) return;
    setSessions((prev) => ({ ...prev, [persona]: next }));
    say(`Balance ${formatNight(next.unshieldedBalance)} NIGHT · ${formatDust(next.dustBalance(new Date()))} DUST for fees`, 'ok');
    await refreshContracts(next);
    setStatus('ready');
  };

  const onPersona = (index: number) => {
    if (index === persona || busy) return;
    setPersona(index);
    say(`persona switched to ${PERSONAS[index]} (genesis seed #${index})`);
  };

  /**
   * Deploy, record, and select — the single implementation.
   *
   * Takes the session explicitly so autorun can use it too. Keeping this in one
   * place matters: when the button and autorun each had their own copy, only the
   * button remembered the contract, so autorun deployments never reached history.
   */
  const deployAndRecord = useCallback(
    async (current: Session): Promise<string | undefined> => {
      const deployedAt = await trackOp('Deploy contract', () =>
        step('Deploy counter (prove + submit)', () => deploy(current)),
      );
      if (!deployedAt) {
        endOp();
        return undefined;
      }
      setAddress(deployedAt);

      // Tag the entry with the chain it belongs to, so a localnet reset can be
      // detected later rather than offering a dead address as usable.
      try {
        remember(deployedAt, await getGenesisHash());
      } catch {
        say('could not record contract in history', 'error');
      }

      opReadingBack();
      setRound((await step('Read round', () => readRound(current, deployedAt))) ?? null);
      endOp();
      await refreshContracts(current);
      return deployedAt;
    },
    [endOp, opReadingBack, refreshContracts, say, step, trackOp],
  );

  const onDeploy = async () => {
    if (!session) return;
    setStatus('working');
    await deployAndRecord(session);
    setStatus('ready');
  };

  /** Switch to a previously deployed contract. */
  const onSelect = async (next: string) => {
    if (!session || next === address) return;
    setStatus('working');
    setAddress(next);
    setRound(null);
    say(`switched to ${next.slice(0, 10)}…`);
    const current = await step('Read round', () => readRound(session, next));
    setRound(current ?? null);
    setStatus('ready');
  };

  const onForget = (target: string) => {
    forget(target);
    if (target === address) {
      setAddress(null);
      setRound(null);
    }
    void refreshContracts(session);
  };

  const onIncrement = async () => {
    if (!session || !address) return;
    setStatus('working');
    const result = await trackOp('increment()', () =>
      step('increment() (prove + submit)', () => increment(session, address)),
    );
    if (!result) {
      endOp();
      return;
    }
    say(`tx ${result.txId.slice(0, 18)}… @ block ${result.blockHeight}`, 'ok');
    opReadingBack();
    const next = await step('Read round', () => readRound(session, address));
    setRound(next ?? null);
    endOp();
    // Refresh the list too, or its per-contract rounds go stale the moment you
    // increment — the card would say 1 while the row still claimed 0.
    await refreshContracts(session);
    setStatus('ready');
  };

  /**
   * `?autorun` runs connect → deploy → increment on load.
   *
   * This exists so the whole flow can be verified in a headless browser, where
   * nothing can click. It is opt-in via the query string and never fires during
   * normal use.
   */
  const autorunStarted = useRef(false);
  useEffect(() => {
    if (autorunStarted.current) return;
    if (!new URLSearchParams(globalThis.location.search).has('autorun')) return;
    autorunStarted.current = true;

    void (async () => {
      say('autorun: create wallet → deploy → increment');
      const s = await step(`Create wallet for ${PERSONAS[0]} (build + sync)`, () => connect(0));
      if (!s) return;
      setSessions((prev) => ({ ...prev, 0: s }));
      say(`Balance ${formatNight(s.unshieldedBalance)} NIGHT · ${formatDust(s.dustBalance(new Date()))} DUST for fees`, 'ok');

      const at = await deployAndRecord(s);
      if (!at) return;

      const result = await trackOp('increment()', () =>
        step('increment() (prove + submit)', () => increment(s, at)),
      );
      if (!result) {
        endOp();
        return;
      }
      say(`tx ${result.txId.slice(0, 18)}… @ block ${result.blockHeight}`, 'ok');
      opReadingBack();
      setRound((await step('Read round', () => readRound(s, at))) ?? null);
      endOp();
      await refreshContracts(s);
      setStatus('ready');
      say('autorun complete', 'ok');
    })();
  }, [deployAndRecord, endOp, opReadingBack, refreshContracts, say, setStatus, step, trackOp]);

  const liveCount = contracts.filter((c) => c.state === 'live').length;
  const walletRows: readonly { k: string; hint: string; addr: string | null; bal: string }[] = [
    {
      k: 'NIGHT',
      hint: "Midnight's native token, held unshielded (publicly visible). Atomic unit: star, 10\u2076 per NIGHT.",
      addr: session?.unshieldedAddress ?? null,
      bal: session ? `${formatNight(session.unshieldedBalance)} NIGHT` : 'not created',
    },
    {
      k: 'shielded',
      hint: 'The same native value held in the shielded pool — amounts and flows are private.',
      addr: session?.shieldedAddress ?? null,
      bal: session ? `${formatNight(session.shieldedBalance)} NIGHT` : 'not created',
    },
    {
      k: 'DUST',
      hint: 'Pays transaction fees. Generated over time by holding NIGHT; cannot be bought or transferred. Atomic unit: speck, 10\u00b9\u2075 per DUST.',
      addr: session?.dustAddress ?? null,
      bal: session ? `${formatDust(session.dustBalance(new Date(ops.now)))} DUST` : 'not created',
    },
  ];

  return (
    <main>
      <header className="topbar">
        <Link to="/" className="brand-home" aria-label="Home">
          <LogoMark className="brand-logo" />
        </Link>
        <div className="brand-text">
          <h1>Counter — the toolchain proof</h1>
          <p className="brand-sub">
            Compile, deploy, prove, submit, read back — entirely client-side; every value below is
            live chain state.
          </p>
        </div>
        <div className="topbar-right">
          {isLocalnet ? (
            <div
              className="net-pill local"
              title="Local development chain — disposable. A restart is a fresh chain; genesis seeds are public."
            >
              <span className="net-glyph" />
              <span>Local chain</span>
              <span className="net-meta">
                {network.networkId}
                {genesis ? ` · ${genesis.slice(0, 10)}…` : ''}
              </span>
            </div>
          ) : (
            <div
              className="net-pill stage"
              title="Stagenet — persistent public test network. State survives; keys are faucet-funded."
            >
              <span className="net-glyph" />
              <span>STAGENET</span>
              <span className="net-meta">{network.networkId}</span>
            </div>
          )}
          <span className="logs-indicator">{logsOn ? 'logs streaming' : 'logs off'}</span>
          <button className="theme-btn" onClick={toggleTheme}>
            {theme === 'dark' ? 'Light' : 'Dark'}
          </button>
        </div>
      </header>

      {/* Two columns so the whole thing fits one screen. Only the activity log,
          the contract list, and the log drawers scroll; the page itself never does. */}
      <div className="columns">
        <div className="col">
          <section className="grid">
            <div className="card">
              <span className="label">Round</span>
              <span className="value">{round === null ? '—' : round.toString()}</span>
            </div>
            <div
              className={address ? 'card copyable' : 'card'}
              title={address ? `${address} — click to copy` : 'No contract selected'}
              onClick={() => {
                if (address) {
                  copyText(address);
                  say('contract address copied');
                }
              }}
            >
              <span className="label">Contract</span>
              <span className="value small">{address ? short(address) : 'not deployed'}</span>
            </div>
            <div className="card">
              <span className="label">Wallet — {PERSONAS[persona]}</span>
              <span className="value small">
                {session ? `${formatNight(session.unshieldedBalance)} NIGHT` : 'not created'}
              </span>
            </div>
          </section>

          <section className="actions">
            <button className="primary" onClick={onConnect} disabled={busy || !!session}>
              {session ? 'Created' : 'Create wallet'}
            </button>
            <button className="secondary" onClick={onDeploy} disabled={busy || !session}>
              {liveCount > 0 ? 'Deploy another' : 'Deploy contract'}
            </button>
            <button
              className="secondary mono"
              onClick={onIncrement}
              disabled={busy || !session || !address}
            >
              increment()
            </button>
          </section>

          <section className="wallet-panel">
            <div className="wallet-head">
              <h2>Wallet</h2>
              {PERSONAS.map((name, i) => (
                <button
                  key={name}
                  className={i === persona ? 'persona active' : 'persona'}
                  onClick={() => onPersona(i)}
                >
                  {name}
                </button>
              ))}
              <span className="wallet-meta">
                {isLocalnet ? `genesis seed #${persona} · public test seed` : 'faucet-funded seed'}
              </span>
            </div>
            {walletRows.map((row) => (
              <div className="wallet-row" key={row.k}>
                <span className="k" title={row.hint}>
                  {row.k}
                </span>
                <span
                  className={row.addr ? 'addr copyable' : 'addr empty'}
                  title={
                    row.addr
                      ? `${row.addr} — click to copy`
                      : `No ${row.k} address yet — create a wallet for ${PERSONAS[persona]}`
                  }
                  onClick={() => {
                    if (row.addr) {
                      copyText(row.addr);
                      say(`${row.k} address copied`);
                    }
                  }}
                >
                  {row.addr ? short(row.addr, 12, 8) : '—'}
                </span>
                <span className="bal">{row.bal}</span>
              </div>
            ))}
          </section>

          <OpBar op={ops.op} lastTiming={ops.lastTiming} now={ops.now} />

          <Contracts
            contracts={contracts}
            active={address}
            busy={busy}
            onSelect={(next) => void onSelect(next)}
            onForget={onForget}
            onRefresh={() => void refreshContracts(session)}
          />

          <section className="log" aria-live="polite" ref={ops.logBox}>
            {ops.log.length === 0 && (
              <div className="guide">
                <p className="muted">
                  <strong>New here?</strong> This page proves the whole Midnight toolchain, live:
                </p>
                <p className="muted">1 · Create a wallet — built in this page from a public test seed, funded with NIGHT by the local chain.</p>
                <p className="muted">2 · Deploy the counter — compiles to a zero-knowledge circuit; the proof is generated on this machine.</p>
                <p className="muted">3 · increment() — a real transaction: proved locally (~0.3s), then included in a block (~18s). Fees are paid in DUST.</p>
                <p className="muted">Everything you see afterwards is read back from the chain, never assumed.</p>
              </div>
            )}
            {ops.log.map((line, i) => (
              <p key={i} className={line.kind}>
                <span>{line.text}</span>
                {line.ms !== undefined && <span className="ms">{(line.ms / 1000).toFixed(1)}s</span>}
              </p>
            ))}
            {busy && <p className="working">working — proving takes ~20s, do not reload</p>}
          </section>
        </div>

        <div className="col">
          <Infrastructure onLogsState={setLogsOn} />
        </div>
      </div>

      <footer>
        <LogoMark className="brand-logo" />
        <p>
          Proofs are generated locally by the proof server — witness data never leaves this
          machine.{' '}
          {isLocalnet
            ? 'This local chain’s wallet uses a well-known public test seed, never a funded key.'
            : 'Stagenet keys are faucet-funded — treat chain state as persistent.'}{' '}
          · proving: local (<span className="mono">{network.proofServer}</span>)
        </p>
      </footer>
    </main>
  );
}
