/**
 * Midnight's denominations, so raw chain integers never reach a screen.
 *
 * NIGHT is the native token; its atomic unit is the STAR, 10^6 per NIGHT.
 * DUST pays transaction fees and is generated by holding NIGHT; its atomic
 * unit is the SPECK, 10^15 per DUST (the resolution is deliberately fine —
 * see the ledger spec, spec/dust.md).
 *
 * Chain and wallet APIs always speak atomic units (stars, specks). Formatting
 * lives here so every page renders the same number the same way.
 */

export const STARS_PER_NIGHT = 1_000_000n;
export const SPECKS_PER_DUST = 1_000_000_000_000_000n;

function formatUnits(atomic: bigint, perWhole: bigint, maxFraction: number): string {
  const negative = atomic < 0n;
  const abs = negative ? -atomic : atomic;
  const whole = abs / perWhole;
  const remainder = abs % perWhole;
  const wholeStr = `${negative ? '-' : ''}${whole.toLocaleString('en-US')}`;
  if (remainder === 0n || maxFraction === 0) return wholeStr;
  const fraction = remainder
    .toString()
    .padStart(perWhole.toString().length - 1, '0')
    .slice(0, maxFraction)
    .replace(/0+$/, '');
  return fraction ? `${wholeStr}.${fraction}` : wholeStr;
}

/** Stars → NIGHT, grouped, fraction only when there is one. */
export function formatNight(stars: bigint, maxFraction = 6): string {
  return formatUnits(stars, STARS_PER_NIGHT, maxFraction);
}

/** Specks → DUST. Full precision is noise on screen; 3 decimals by default. */
export function formatDust(specks: bigint, maxFraction = 3): string {
  return formatUnits(specks, SPECKS_PER_DUST, maxFraction);
}
